# Generated by Django 3.2.8 on 2021-10-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(default='', max_length=45),
        ),
    ]
