# Generated by Django 3.2.8 on 2021-10-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=45)),
                ('user_email', models.EmailField(max_length=200, unique=True)),
                ('user_password', models.CharField(max_length=200)),
                ('user_phone_num', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='etc',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.DeleteModel(
            name='Password',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
