# Generated by Django 3.2.8 on 2021-10-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211022_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_phone_num',
            new_name='phone_num',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='reated_at',
            new_name='related_at',
        ),
    ]
