# Generated by Django 3.2.8 on 2021-10-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211022_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='related_at',
            new_name='created_at',
        ),
    ]
