# Generated by Django 3.2.8 on 2021-10-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=300, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=13)),
                ('personal_info', models.TextField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
